# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-08 15:04
from __future__ import unicode_literals

from django.db import migrations


def create_sample_data(apps, schema_editor):
    KeySetModel = apps.get_model('keyset_pagination', 'KeySetModel')
    for i in range(1, 26):
        KeySetModel.objects.create(name='name %s'% i)


def remove_sample_data(apps, schema_editor):
    KeySetModel = apps.get_model('keyset_pagination', 'KeySetModel')
    KeySetModel.objects.all.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('keyset_pagination', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_data, reverse_code=migrations.RunPython.noop)
    ]
